import { CSSProperties } from "react";
import { colors, fonts } from "./tokens";

export const editorialStyles = {
  eyebrow: {
    fontFamily: fonts.franklin,
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.16em",
    textTransform: "uppercase" as const,
    color: colors.faintLabel,
  },
  gameTitle: {
    fontFamily: fonts.serif,
    fontWeight: 700,
    fontSize: 46,
    lineHeight: 1.02,
    margin: 0,
    color: colors.ink,
  },
  dek: {
    fontFamily: fonts.serif,
    fontStyle: "italic" as const,
    fontSize: 18,
    color: colors.meta,
    margin: "10px 0 0",
  },
  btnPrimary: {
    fontFamily: fonts.franklin,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    background: colors.ink,
    color: colors.paper,
    border: `1px solid ${colors.ink}`,
    padding: "11px 18px",
    cursor: "pointer",
    borderRadius: 0,
  } as CSSProperties,
  btnOutline: {
    fontFamily: fonts.franklin,
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    background: "none",
    color: colors.ink,
    border: `1px solid ${colors.ink}`,
    padding: "11px 18px",
    cursor: "pointer",
    borderRadius: 0,
  } as CSSProperties,
  btnClear: {
    fontFamily: fonts.franklin,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.1em",
    textTransform: "uppercase" as const,
    background: "none",
    color: colors.meta,
    border: "1px solid #d2d2d2",
    padding: "9px 15px",
    cursor: "pointer",
    borderRadius: 0,
  } as CSSProperties,
  btnDanger: {
    fontFamily: fonts.franklin,
    fontSize: 11,
    fontWeight: 600,
    letterSpacing: "0.1em",
    textTransform: "uppercase" as const,
    background: "none",
    color: colors.accent,
    border: `1px solid ${colors.accent}`,
    padding: "9px 15px",
    cursor: "pointer",
    borderRadius: 0,
  } as CSSProperties,
  scoreInput: {
    width: "100%",
    border: "none",
    background: "transparent",
    outline: "none",
    textAlign: "right" as const,
    fontFamily: fonts.numbers,
    fontSize: 20,
    color: colors.body,
    padding: "10px 6px",
    boxSizing: "border-box" as const,
    minHeight: 48,
  } as CSSProperties,
  playerNameInput: {
    fontFamily: fonts.franklin,
    fontSize: 13,
    fontWeight: 700,
    color: colors.ink,
    textAlign: "right" as const,
    border: "none",
    background: "transparent",
    outline: "none",
    width: "100%",
    minWidth: 0,
    padding: 0,
  } as CSSProperties,
  addPlayerInput: {
    fontFamily: fonts.franklin,
    fontSize: 14,
    padding: "10px 13px",
    border: `1px solid ${colors.inputBorder}`,
    outline: "none",
    width: 220,
    color: colors.ink,
    borderRadius: 0,
    boxSizing: "border-box" as const,
  } as CSSProperties,
  pageContainer: {
    maxWidth: 1180,
    margin: "0 auto",
    padding: "0 clamp(16px, 5vw, 40px)",
    boxSizing: "border-box" as const,
    width: "100%",
  } as CSSProperties,
  twoColumnGrid: (isNarrow: boolean): CSSProperties => ({
    display: "grid",
    gridTemplateColumns: isNarrow ? "1fr" : "1fr 312px",
    gap: isNarrow ? 32 : 48,
    padding: "34px 0 80px",
    alignItems: "start",
  }),
};

export function getOrdinal(rank: number): string {
  const suffixes = ["th", "st", "nd", "rd"];
  const v = rank % 100;
  const suffix = suffixes[(v - 20) % 10] || suffixes[v] || suffixes[0];
  return `${rank}${suffix}`;
}
